# Generated by Django 5.2.17 on 2026-08-19 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('instituicao_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subunidades', to='instituicoes.instituicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VinculoInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('individual', 'Usuário individual'), ('medico', 'Médico'), ('educador_fisico', 'Educador físico'), ('integrante', 'Integrante (institucional)'), ('medico_do_trabalho', 'Médico do trabalho'), ('gerente', 'Gerente/Comandante')], max_length=30)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='instituicoes.instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_institucionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'instituicao')},
            },
        ),
    ]
